# Generated by Django 5.2.4 on 2025-07-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
