# Generated by Django 5.2.1 on 2025-08-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_disciplina_carga_horaria'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.turma'),
        ),
    ]
