# Generated by Django 5.1.7 on 2025-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=100)),
                ('data_entrega', models.DateField()),
                ('concluido', models.BooleanField(default=False)),
                ('prioridade', models.IntegerField()),
            ],
        ),
    ]
