# Generated by Django 5.2.5 on 2025-08-19 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATIVIDADE', 'Atividade'), ('MATERIAL', 'Material de Apoio')], max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='itens_academicos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_academicos', to='disciplina.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('itemacademico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemacademico.itemacademico')),
                ('data_entrega', models.DateTimeField()),
            ],
            bases=('itemacademico.itemacademico',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('itemacademico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemacademico.itemacademico')),
            ],
            bases=('itemacademico.itemacademico',),
        ),
    ]
