# Generated by Django 5.2.1 on 2025-08-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0003_disciplina_turma'),
        ('itemacademico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemacademico',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_academicos', to='disciplina.disciplina'),
        ),
    ]
