# Generated by Django 5.2.5 on 2025-08-21 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
        ('disciplina', '0003_disciplina_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['data_entrega', 'prioridade'], 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='checklist',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='data_entrega',
            field=models.DateField(verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
