# Generated by Django 5.1.7 on 2025-08-21 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('AA', 'AA'), ('AB', 'AB'), ('BA', 'BA'), ('BII', 'BII'), ('AII', 'AII')], max_length=4)),
                ('ano', models.CharField(choices=[('1° Ano', '1° Ano'), ('2° Ano', '2° Ano'), ('3° Ano', '3° Ano')], max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('codigo_convite', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_turmas', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, related_name='turmas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
