# Generated by Django 5.2.1 on 2025-06-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('AA', 'AA'), ('AB', 'AB'), ('BA', 'BA'), ('BII', 'BII'), ('AII', 'AII')], max_length=4)),
                ('ano', models.CharField(choices=[('1° Ano', '1° Ano'), ('2° Ano', '2° Ano'), ('3° Ano', '3° Ano')], max_length=10)),
                ('lider', models.CharField(default='Sem líder', max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
    ]
