# Generated by Django 5.2.5 on 2025-08-30 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='lider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lider_turmas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
