# Generated by Django 5.2.1 on 2025-09-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('turma', '0002_alter_turma_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_turmas', to='aluno.aluno'),
        ),
    ]
