# Generated by Django 5.2.1 on 2025-09-17 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0003_alter_turma_lider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
