# Generated by Django 5.2.1 on 2025-08-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
        ('itemacademico', '0003_alter_itemacademico_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='comentario.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemacademico.itemacademico'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(),
        ),
    ]
